/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import V1APIGroupList from '../com.appscode.voyager.client.models/V1APIGroupList';

/**
* Apis service.
* @module com.appscode.voyager.client/com.appscode.voyager.client.apis/ApisApi
* @version 1.0-SNAPSHOT
*/
export default class ApisApi {

    /**
    * Constructs a new ApisApi. 
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.apis/ApisApi
    * @class
    * @param {module:com.appscode.voyager.client/ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:com.appscode.voyager.client/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAPIVersions operation.
     * @callback module:com.appscode.voyager.client/com.appscode.voyager.client.apis/ApisApi~getAPIVersionsCallback
     * @param {String} error Error message, if any.
     * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1APIGroupList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get available API versions
     * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.apis/ApisApi~getAPIVersionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1APIGroupList}
     */
    getAPIVersions(callback) {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json', 'application/yaml', 'application/vnd.kubernetes.protobuf'];
      let accepts = ['application/json', 'application/yaml', 'application/vnd.kubernetes.protobuf'];
      let returnType = V1APIGroupList;

      return this.apiClient.callApi(
        '/apis/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
