/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import IntstrIntOrString from './IntstrIntOrString';
import V1beta1AuthOption from './V1beta1AuthOption';





/**
* The V1beta1FrontendRule model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1FrontendRule
* @version 1.0-SNAPSHOT
*/
export default class V1beta1FrontendRule {
    /**
    * Constructs a new <code>V1beta1FrontendRule</code>.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1FrontendRule
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1FrontendRule</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1FrontendRule} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1FrontendRule} The populated <code>V1beta1FrontendRule</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1FrontendRule();

            
            
            

            if (data.hasOwnProperty('auth')) {
                obj['auth'] = V1beta1AuthOption.constructFromObject(data['auth']);
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = IntstrIntOrString.constructFromObject(data['port']);
            }
            if (data.hasOwnProperty('rules')) {
                obj['rules'] = ApiClient.convertToType(data['rules'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1AuthOption} auth
    */
    auth = undefined;
    /**
    * Port indicates the frontend port where HAProxy is listening for connection
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/IntstrIntOrString} port
    */
    port = undefined;
    /**
    * Serialized rules
    * @member {Array.<String>} rules
    */
    rules = undefined;








}


