/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import IntstrIntOrString from './IntstrIntOrString';
import V1beta1IngressBackend from './V1beta1IngressBackend';





/**
* The V1beta1TCPIngressRuleValue model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1TCPIngressRuleValue
* @version 1.0-SNAPSHOT
*/
export default class V1beta1TCPIngressRuleValue {
    /**
    * Constructs a new <code>V1beta1TCPIngressRuleValue</code>.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1TCPIngressRuleValue
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1TCPIngressRuleValue</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1TCPIngressRuleValue} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1TCPIngressRuleValue} The populated <code>V1beta1TCPIngressRuleValue</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1TCPIngressRuleValue();

            
            
            

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('alpn')) {
                obj['alpn'] = ApiClient.convertToType(data['alpn'], ['String']);
            }
            if (data.hasOwnProperty('backend')) {
                obj['backend'] = V1beta1IngressBackend.constructFromObject(data['backend']);
            }
            if (data.hasOwnProperty('noTLS')) {
                obj['noTLS'] = ApiClient.convertToType(data['noTLS'], 'Boolean');
            }
            if (data.hasOwnProperty('nodePort')) {
                obj['nodePort'] = IntstrIntOrString.constructFromObject(data['nodePort']);
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = IntstrIntOrString.constructFromObject(data['port']);
            }
        }
        return obj;
    }

    /**
    * The network address to listen TCP connections on.
    * @member {String} address
    */
    address = undefined;
    /**
    * Application-Layer Protocol Negotiation (ALPN) is a Transport Layer Security (TLS) extension for application layer protocol negotiation. ALPN allows the application layer to negotiate which protocol should be performed over a secure connection in a manner which avoids additional round trips and which is independent of the application layer protocols. It is used by HTTP/2. If provided a list of alpn will be added to port as alpn option1,option2,... If SecretName is Provided this secret will be used to terminate SSL with alpn options. If Secret name is not provided backend server is responsible for handling SSL.
    * @member {Array.<String>} alpn
    */
    alpn = undefined;
    /**
    * Backend to forward the requests.
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressBackend} backend
    */
    backend = undefined;
    /**
    * Set noTLS = true to force plain text. Else, auto detect like present
    * @member {Boolean} noTLS
    */
    noTLS = undefined;
    /**
    * Specifies the node port of the referenced service.
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/IntstrIntOrString} nodePort
    */
    nodePort = undefined;
    /**
    * port to listen tcp connections.
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/IntstrIntOrString} port
    */
    port = undefined;








}


