/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1beta1BasicAuth from './V1beta1BasicAuth';
import V1beta1TLSAuth from './V1beta1TLSAuth';





/**
* The V1beta1AuthOption model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1AuthOption
* @version 1.0-SNAPSHOT
*/
export default class V1beta1AuthOption {
    /**
    * Constructs a new <code>V1beta1AuthOption</code>.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1AuthOption
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1AuthOption</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1AuthOption} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1AuthOption} The populated <code>V1beta1AuthOption</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1AuthOption();

            
            
            

            if (data.hasOwnProperty('basic')) {
                obj['basic'] = V1beta1BasicAuth.constructFromObject(data['basic']);
            }
            if (data.hasOwnProperty('tls')) {
                obj['tls'] = V1beta1TLSAuth.constructFromObject(data['tls']);
            }
        }
        return obj;
    }

    /**
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1BasicAuth} basic
    */
    basic = undefined;
    /**
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1TLSAuth} tls
    */
    tls = undefined;








}


