/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1Affinity from './V1Affinity';
import V1LocalObjectReference from './V1LocalObjectReference';
import V1ResourceRequirements from './V1ResourceRequirements';
import V1Toleration from './V1Toleration';
import V1beta1FrontendRule from './V1beta1FrontendRule';
import V1beta1HTTPIngressBackend from './V1beta1HTTPIngressBackend';
import V1beta1IngressRule from './V1beta1IngressRule';
import V1beta1IngressTLS from './V1beta1IngressTLS';





/**
* The V1beta1IngressSpec model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressSpec
* @version 1.0-SNAPSHOT
*/
export default class V1beta1IngressSpec {
    /**
    * Constructs a new <code>V1beta1IngressSpec</code>.
    * IngressSpec describes the Ingress the user wishes to exist.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressSpec
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1IngressSpec</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressSpec} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressSpec} The populated <code>V1beta1IngressSpec</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1IngressSpec();

            
            
            

            if (data.hasOwnProperty('affinity')) {
                obj['affinity'] = V1Affinity.constructFromObject(data['affinity']);
            }
            if (data.hasOwnProperty('backend')) {
                obj['backend'] = V1beta1HTTPIngressBackend.constructFromObject(data['backend']);
            }
            if (data.hasOwnProperty('externalIPs')) {
                obj['externalIPs'] = ApiClient.convertToType(data['externalIPs'], ['String']);
            }
            if (data.hasOwnProperty('frontendRules')) {
                obj['frontendRules'] = ApiClient.convertToType(data['frontendRules'], [V1beta1FrontendRule]);
            }
            if (data.hasOwnProperty('imagePullSecrets')) {
                obj['imagePullSecrets'] = ApiClient.convertToType(data['imagePullSecrets'], [V1LocalObjectReference]);
            }
            if (data.hasOwnProperty('loadBalancerSourceRanges')) {
                obj['loadBalancerSourceRanges'] = ApiClient.convertToType(data['loadBalancerSourceRanges'], ['String']);
            }
            if (data.hasOwnProperty('nodeSelector')) {
                obj['nodeSelector'] = ApiClient.convertToType(data['nodeSelector'], {'String': 'String'});
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = V1ResourceRequirements.constructFromObject(data['resources']);
            }
            if (data.hasOwnProperty('rules')) {
                obj['rules'] = ApiClient.convertToType(data['rules'], [V1beta1IngressRule]);
            }
            if (data.hasOwnProperty('schedulerName')) {
                obj['schedulerName'] = ApiClient.convertToType(data['schedulerName'], 'String');
            }
            if (data.hasOwnProperty('tls')) {
                obj['tls'] = ApiClient.convertToType(data['tls'], [V1beta1IngressTLS]);
            }
            if (data.hasOwnProperty('tolerations')) {
                obj['tolerations'] = ApiClient.convertToType(data['tolerations'], [V1Toleration]);
            }
        }
        return obj;
    }

    /**
    * If specified, the pod's scheduling constraints
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1Affinity} affinity
    */
    affinity = undefined;
    /**
    * A default backend capable of servicing requests that don't match any rule. At least one of 'backend' or 'rules' must be specified. This field is optional to allow the loadbalancer controller or defaulting logic to specify a global default.
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1HTTPIngressBackend} backend
    */
    backend = undefined;
    /**
    * externalIPs is a list of IP addresses for which nodes in the cluster will also accept traffic for this service.  These IPs are not managed by Kubernetes.  The user is responsible for ensuring that traffic arrives at a node with this IP.  A common example is external load-balancers that are not part of the Kubernetes system.
    * @member {Array.<String>} externalIPs
    */
    externalIPs = undefined;
    /**
    * Frontend rules specifies a set of rules that should be applied in HAProxy frontend configuration. The set of keywords are from here https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4.1 Only frontend sections can be applied here. It is up to user to provide valid set of rules. This allows acls or other options in frontend sections in HAProxy config. Frontend rules will be mapped with Ingress Rules according to port.
    * @member {Array.<module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1FrontendRule>} frontendRules
    */
    frontendRules = undefined;
    /**
    * ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec. If specified, these secrets will be passed to individual puller implementations for them to use. For example, in the case of docker, only DockerConfig type secrets are honored. More info: https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod
    * @member {Array.<module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1LocalObjectReference>} imagePullSecrets
    */
    imagePullSecrets = undefined;
    /**
    * Optional: If specified and supported by the platform, this will restrict traffic through the cloud-provider load-balancer will be restricted to the specified client IPs. This field will be ignored if the cloud-provider does not support the feature. https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/
    * @member {Array.<String>} loadBalancerSourceRanges
    */
    loadBalancerSourceRanges = undefined;
    /**
    * NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
    * @member {Object.<String, String>} nodeSelector
    */
    nodeSelector = undefined;
    /**
    * Compute Resources required by the sidecar container.
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1ResourceRequirements} resources
    */
    resources = undefined;
    /**
    * A list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend.
    * @member {Array.<module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressRule>} rules
    */
    rules = undefined;
    /**
    * If specified, the pod will be dispatched by specified scheduler. If not specified, the pod will be dispatched by default scheduler.
    * @member {String} schedulerName
    */
    schedulerName = undefined;
    /**
    * TLS is the TLS configuration. Currently the Ingress only supports a single TLS port, 443, and assumes TLS termination. If multiple members of this list specify different hosts, they will be multiplexed on the same port according to the hostname specified through the SNI TLS extension.
    * @member {Array.<module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressTLS>} tls
    */
    tls = undefined;
    /**
    * If specified, the pod's tolerations.
    * @member {Array.<module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1Toleration>} tolerations
    */
    tolerations = undefined;








}


