/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1Time from './V1Time';





/**
* The V1beta1CertificateCondition model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1CertificateCondition
* @version 1.0-SNAPSHOT
*/
export default class V1beta1CertificateCondition {
    /**
    * Constructs a new <code>V1beta1CertificateCondition</code>.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1CertificateCondition
    * @class
    * @param type {String} request approval state, currently Approved or Denied.
    */

    constructor(type) {
        

        
        

        this['type'] = type;

        
    }

    /**
    * Constructs a <code>V1beta1CertificateCondition</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1CertificateCondition} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1CertificateCondition} The populated <code>V1beta1CertificateCondition</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1CertificateCondition();

            
            
            

            if (data.hasOwnProperty('lastUpdateTime')) {
                obj['lastUpdateTime'] = V1Time.constructFromObject(data['lastUpdateTime']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * timestamp for the last update to this condition
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1Time} lastUpdateTime
    */
    lastUpdateTime = undefined;
    /**
    * human readable message with details about the request state
    * @member {String} message
    */
    message = undefined;
    /**
    * brief reason for the request state
    * @member {String} reason
    */
    reason = undefined;
    /**
    * request approval state, currently Approved or Denied.
    * @member {String} type
    */
    type = undefined;








}


