/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1beta1LocalTypedReference from './V1beta1LocalTypedReference';





/**
* The V1beta1HTTPChallengeProvider model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1HTTPChallengeProvider
* @version 1.0-SNAPSHOT
*/
export default class V1beta1HTTPChallengeProvider {
    /**
    * Constructs a new <code>V1beta1HTTPChallengeProvider</code>.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1HTTPChallengeProvider
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1HTTPChallengeProvider</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1HTTPChallengeProvider} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1HTTPChallengeProvider} The populated <code>V1beta1HTTPChallengeProvider</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1HTTPChallengeProvider();

            
            
            

            if (data.hasOwnProperty('ingress')) {
                obj['ingress'] = V1beta1LocalTypedReference.constructFromObject(data['ingress']);
            }
        }
        return obj;
    }

    /**
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1LocalTypedReference} ingress
    */
    ingress = undefined;








}


