/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1beta1DNSChallengeProvider from './V1beta1DNSChallengeProvider';
import V1beta1HTTPChallengeProvider from './V1beta1HTTPChallengeProvider';





/**
* The V1beta1ChallengeProvider model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1ChallengeProvider
* @version 1.0-SNAPSHOT
*/
export default class V1beta1ChallengeProvider {
    /**
    * Constructs a new <code>V1beta1ChallengeProvider</code>.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1ChallengeProvider
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1ChallengeProvider</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1ChallengeProvider} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1ChallengeProvider} The populated <code>V1beta1ChallengeProvider</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1ChallengeProvider();

            
            
            

            if (data.hasOwnProperty('dns')) {
                obj['dns'] = V1beta1DNSChallengeProvider.constructFromObject(data['dns']);
            }
            if (data.hasOwnProperty('http')) {
                obj['http'] = V1beta1HTTPChallengeProvider.constructFromObject(data['http']);
            }
        }
        return obj;
    }

    /**
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1DNSChallengeProvider} dns
    */
    dns = undefined;
    /**
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1HTTPChallengeProvider} http
    */
    http = undefined;








}


