/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1beta1DNSChallengeProvider model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1DNSChallengeProvider
* @version 1.0-SNAPSHOT
*/
export default class V1beta1DNSChallengeProvider {
    /**
    * Constructs a new <code>V1beta1DNSChallengeProvider</code>.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1DNSChallengeProvider
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1DNSChallengeProvider</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1DNSChallengeProvider} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1DNSChallengeProvider} The populated <code>V1beta1DNSChallengeProvider</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1DNSChallengeProvider();

            
            
            

            if (data.hasOwnProperty('credentialSecretName')) {
                obj['credentialSecretName'] = ApiClient.convertToType(data['credentialSecretName'], 'String');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} credentialSecretName
    */
    credentialSecretName = undefined;
    /**
    * DNS Provider from the list https://github.com/appscode/voyager/blob/master/docs/tasks/certificate/providers.md
    * @member {String} provider
    */
    provider = undefined;








}


