/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1LocalObjectReference from './V1LocalObjectReference';
import V1beta1VaultStore from './V1beta1VaultStore';





/**
* The V1beta1CertificateStorage model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1CertificateStorage
* @version 1.0-SNAPSHOT
*/
export default class V1beta1CertificateStorage {
    /**
    * Constructs a new <code>V1beta1CertificateStorage</code>.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1CertificateStorage
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1CertificateStorage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1CertificateStorage} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1CertificateStorage} The populated <code>V1beta1CertificateStorage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1CertificateStorage();

            
            
            

            if (data.hasOwnProperty('secret')) {
                obj['secret'] = V1LocalObjectReference.constructFromObject(data['secret']);
            }
            if (data.hasOwnProperty('vault')) {
                obj['vault'] = V1beta1VaultStore.constructFromObject(data['vault']);
            }
        }
        return obj;
    }

    /**
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1LocalObjectReference} secret
    */
    secret = undefined;
    /**
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1VaultStore} vault
    */
    vault = undefined;








}


