/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1beta1LocalTypedReference from './V1beta1LocalTypedReference';





/**
* The V1beta1IngressTLS model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressTLS
* @version 1.0-SNAPSHOT
*/
export default class V1beta1IngressTLS {
    /**
    * Constructs a new <code>V1beta1IngressTLS</code>.
    * IngressTLS describes the transport layer security associated with an Ingress.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressTLS
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1IngressTLS</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressTLS} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressTLS} The populated <code>V1beta1IngressTLS</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1IngressTLS();

            
            
            

            if (data.hasOwnProperty('hosts')) {
                obj['hosts'] = ApiClient.convertToType(data['hosts'], ['String']);
            }
            if (data.hasOwnProperty('ref')) {
                obj['ref'] = V1beta1LocalTypedReference.constructFromObject(data['ref']);
            }
            if (data.hasOwnProperty('secretName')) {
                obj['secretName'] = ApiClient.convertToType(data['secretName'], 'String');
            }
        }
        return obj;
    }

    /**
    * Hosts are a list of hosts included in the TLS certificate. The values in this list must match the name/s used in the tlsSecret. Defaults to the wildcard host setting for the loadbalancer controller fulfilling this Ingress, if left unspecified.
    * @member {Array.<String>} hosts
    */
    hosts = undefined;
    /**
    * Ref to used tls termination.
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1LocalTypedReference} ref
    */
    ref = undefined;
    /**
    * SecretName is the name of the secret used to terminate SSL traffic on 443. Field is left optional to allow SSL routing based on SNI hostname alone. If the SNI host in a listener conflicts with the \"Host\" header field used by an IngressRule, the SNI host is used for termination and value of the Host header is used for routing. Deprecated
    * @member {String} secretName
    */
    secretName = undefined;








}


