/**
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1LoadBalancerStatus from './V1LoadBalancerStatus';





/**
* The V1beta1IngressStatus model module.
* @module com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressStatus
* @version 1.0-SNAPSHOT
*/
export default class V1beta1IngressStatus {
    /**
    * Constructs a new <code>V1beta1IngressStatus</code>.
    * IngressStatus describe the current state of the Ingress.
    * @alias module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressStatus
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1IngressStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressStatus} obj Optional instance to populate.
    * @return {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1beta1IngressStatus} The populated <code>V1beta1IngressStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1IngressStatus();

            
            
            

            if (data.hasOwnProperty('loadBalancer')) {
                obj['loadBalancer'] = V1LoadBalancerStatus.constructFromObject(data['loadBalancer']);
            }
        }
        return obj;
    }

    /**
    * LoadBalancer contains the current status of the load-balancer.
    * @member {module:com.appscode.voyager.client/com.appscode.voyager.client.models/V1LoadBalancerStatus} loadBalancer
    */
    loadBalancer = undefined;








}


